### ISSUE TITLE
How to make work with prettier + vue?

### ISSUE THREAD

**Issue by amritk** [schoero/eslint-plugin-readable-tailwind#45] opened 2024-06-09 08:55 UTC
I'm not sure what I'm missing from my setup, eslint and the plugin work well.

![image](https://github.com/schoero/eslint-plugin-readable-tailwind/assets/2039539/3e10149c-0a86-4fff-877c-cdaa391022ab)

But right after prettier runs, it joins the line back together

![image](https://github.com/schoero/eslint-plugin-readable-tailwind/assets/2039539/517d6b6d-9018-458f-ba8f-31b791fa2405)

Is there a way to disable this in the prettier config?

```js
// .prettierrc
{
  "plugins": ["@trivago/prettier-plugin-sort-imports"],
  "trailingComma": "all",
  "quoteProps": "consistent",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "singleAttributePerLine": true,
  "bracketSameLine": true,
  "importOrder": ["^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
```

**Comment by schoero** [comment] 2024-06-10 05:28
I don't think this can be solved unfortunately. Prettier is [not very configurable](https://prettier.io/docs/en/option-philosophy)  by design. As far as I know, the only way to ignore parts of a file is to work with [ignore comments](https://prettier.io/docs/en/ignore).

**Comment by amritk** [comment] 2024-06-12 20:21
dang!

**Comment by schoero** [comment] 2024-06-19 05:43
I'm closing this issue, unfortunately there is nothing I can do in this library to fix this.

**Closed by schoero** 2024-06-19 05:43 UTC

**Comment by lolmaus** [comment] 2024-06-24 17:22
So what is the official recomendation? Use either Prettier or subj, but never both?

**Comment by schoero** [comment] 2024-06-24 17:49
I can't make a recommendation, it depends on your preference.

If you want to stick with prettier and don't want to put `// prettier-ignore` comments everywhere, this plugin doesn't work for you. However, if you find the benefits of this plugin to outweigh those of Prettier, you might decide otherwise.

I'm not aware of any workarounds for this issue, but I'd be happy to be proven wrong.

**Comment by lolmaus** [comment] 2024-06-25 08:48
Can this trasnform be a Prettier plugin in the first place?

**Comment by schoero** [comment] 2024-06-25 09:09
Prettier works very differently internally compared to ESLint, so I would assume converting it to a Prettier plugin would be a big task.

I personally don't use Prettier because of its lack of configurability, so someone else will have to take on this task.

**Comment by lolmaus** [comment] 2024-06-27 11:54
Thank you four your kind explanations and development effort. :bowing_man:

**Comment by lolmaus** [comment] 2024-06-27 11:55
PS I wish the matter of avoiding Prettier was a personal choice...

**Comment by amritk** [comment] 2024-06-27 21:37
If you just run prettier through eslint instead I believe you can get around this.

**Comment by VityaSchel** [comment] 2025-06-08 10:01
> If you just run prettier through eslint instead I believe you can get around this.

Can you elaborate on this please? I am running prettier through eslint but it still joins lines

**Comment by VityaSchel** [comment] 2025-06-08 10:03
I got around this by removing https://github.com/tailwindlabs/prettier-plugin-tailwindcss

**Comment by CHC383** [comment] 2025-07-11 01:00
If you prefer Prettier (like the features provided by [tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)), another option is to turn off the line wrapping rule. This way you will still be able to benefit from the other ESLint rules of this plugin.

```
// eslint.config.js
rules: {
  "better-tailwindcss/enforce-consistent-line-wrapping": "off", // Conflict with prettier
},
```
